on:
  push:
    paths:
      - ProgramasEstructuradeDatos/Listas_circulares/  # Ruta relativa al archivo específico
  pull_request:
    paths:
      - ProgramasEstructuradeDatos/Listas_circulares/ # Ruta relativa al archivo específico

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Compilar el código, supongamos que produce un ejecutable "mi_programa"
    - name: Compile code
      run: gcc -o exec circulares2.c

    # Ejecutar el ejecutable
    - name: Run executable
      run: ./exec

    # Otras tareas, como pruebas, análisis, etc.
    - name: Run tests
      run: ./tests.sh
